#!/usr/bin/env bash
# Script for transferring a file from a client to another server.
# Requires four arguments:
#+    1. Path to the file to be transferred.
#+    2. IP address of the destination server.
#+    3. Username used for the scp connection.
#+    4. Path to the SSH private key used by scp.

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi

